# Site settings
title: Kevin blogs about learning how to code.
header-img: img/home-bg.png
email: kevikim33@gmail.com
copyright_name: kevinYCKim33
description: > # this means to ignore newlines until "baseurl:"
  Kevin rambles about programming he learned.  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kevinYCKim33
learn_profile: kevinYCKim33
email_username: kevikim33@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
